### ISSUE TITLE
TODO List for this project

### ISSUE THREAD

**Issue by SebaGraz** [mmider/BridgeSDEInference.jl#64]
Here is a TODO list concerning the application of the guided proposals for the Jansen and Rit model. I will try to work on these. 
 
- [ ] More freedom on the choice of transition kernels and priors in the MH updates. We have noticed strong dependences between the parameters and it makes sense to try to update them together with a MH step with a multivariate Gaussian transition kernel with high covariance. 
- [ ] More freedom on how to do `fusion` of kernels. We would like to fuse only some parameters. Right now if `fusion` is on, we get the following error 
` matrix is not Hermitian; Cholesky factorization failed `
- [ ] inspect the above error
- [ ] Conjugate update is very slow probably due to some high dimensional (15 X 15) Static Matrices created in this step. Change implementation
- [ ] More freedom on doing more than one conjugate step which means having more than one set of functions `phi`. (In our case this can be used to do a conjugate step for `A`,`B` and another one for `\mu_y`)
- [ ] Update documentation regarding the project (I will do it very soon)
- [ ] If the augmentation time grid is too coarse, there are some numerical issues. Setting a finer grid solves the issue with the drawback of slowing down the algorithm. Other possible solutions might be changing the space-time transformation when evaluating the likelihood or explore the splitting integration scheme (as suggested by Frank).

**Comment by mschauer** [comment]
> matrix is not Hermitian; Cholesky factorization failed

Somewhere maybe a `chol(Hermitian(x))` needed instead of `chol(x)`
